### ISSUE TITLE
I wish. When you search up somebody name It tells you they're date of birth.

### ISSUE THREAD

**Issue by githubfan6754** [Linesmerrill/police-cad#108]
**Describe the solution you'd like**

**Implementation Details**
Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)

**Possible Side Effects**
What are some of the adverse reactions that adding this could bring to the website?

**Comment by Linesmerrill** [comment]
Yeah great suggestion! We had it like this before but wanted to make it more official and since we had so many duplicates of names, for example John Smith we had over 200+ duplicates. We decided that using the date of birth not only gave it a bit more of realism, but also satisfied our need to reduce the duplicates. For now we won't be changing back to this but in the future it could be something we include in an individual community version of the website.
