### ISSUE TITLE
Not working> After you search someone up it logs you out or it loads for 10minutes.

### ISSUE THREAD

**Issue by officerhowreya** [Linesmerrill/police-cad#131]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Linesmerrill** [comment]
Thank you for posting this bug! Yeah we have seen a lot of traffic over the past few days and have had to continually update our infrastructure. This is logging people out because the web server is just overloaded with traffic. We are working to scale up the number of servers we have to better handle the traffic. We appreciate your patience while we work through this. We should have a better working solution in the next 24-48 hours (preferably sooner) .

**Comment by Linesmerrill** [comment]
We have upgraded the servers and are happy to report that we have not seen this slow behavior over the past few days. We have monitoring setup that will alert us if this does happen in the future. So thank you again for bringing this to our attention.
