### ISSUE TITLE
Error after making a single change

### ISSUE THREAD

**Issue by PLOKMJNB** [Linesmerrill/police-cad#179]
SyntaxError: missing ) after argument list in C:\Users\Danish G7\Desktop\police-cad-master\views\civ-dashboard.ejs while compiling ejs

**Comment by Linesmerrill** [comment]
Hi @PLOKMJNB can you provide us with a bit more information so we can look into this?

**Describe the bug**
[_A clear and concise description of what the bug is._]

- 

**To Reproduce**
[_Steps to reproduce the behavior:_]
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by PLOKMJNB** [comment]
**Describe the bug**
SyntaxError: missing ) after argument list in C:\Users\Danish G7\Desktop\police-cad-master\views\civ-dashboard.ejs while compiling ejs


**To Reproduce**

1. Go to 'civ-dashboard.ejs'
2. make any change (I was changing names)
3. Go to 'http://localhost:8080'
4. then to Civilian dashboard
4. See error
 
**Expected behavior**
Civilian dashboard 

**Screenshots**
https://imgur.com/a/tJwwgKJ

**Desktop:**
* OS: [Windows 10 (1909)]
* Browser [Edge(Chromium)]
* Version [81.0.416.58]

**Comment by Linesmerrill** [comment]
It appears that you may have some invalid ejs within your code. This does not appear to be a bug with our code base but rather with your forked version. I would suggest you make the smallest number of changes as possible to debug this issue(s).

1) Compare what you have changed with our master branch
2) Debug the issues and see where you removed a `)` from the `civ-dashboard.ejs` file

**Please Note:** While we love having people fork our codebase we cannot provide step-by-step instructions on changes that you have made to your own code. Please try to keep these issues related to our working codebase and not a modified version you are working with. Thank you! 👍

**Comment by PLOKMJNB** [comment]
I think its VSC's auto formatting that broke the code, I changed only text than Ctrl-S, I'll turn if off and try again

**Comment by PLOKMJNB** [comment]
Yep it was Visual Studio Code's auto formatting, I switched to Sublime and it works flawlessly, sorry about that
