### ISSUE TITLE
Bug with Lines Police Cad

### ISSUE THREAD

**Issue by MedicUnit1** [Linesmerrill/police-cad#204]
**Describe the bug**
[_A clear and concise description of what the bug is._]
lines police cad busted
- 

**To Reproduce**
[_Steps to reproduce the behavior:_]
1. Go to '...'name database
2. Click on '....'name database
3. Scroll down to '....'name database
4. See errorno name show

**Expected behavior**
[_A clear and concise description of what you expected to happen._]
bullcrap dont show info
- 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**
 - OS: [e.g. iB&O]
 - Browser [e.g. chrome]

**Additional context**
[_Add any other context about the problem here._]
please let me open database to view names
-

**Comment by Linesmerrill** [comment]
Hi @MedicUnit1 thanks for creating this bug ticket. We apologize for any inconvenience with this issue. Before we get started looking into this issue, can you please provide us with a few more details?

1. Are you in a community or not?
  A. You can verify whether you are in a community by either navigating to the community menu in the top right, or when you search for a name if the popup window includes the 'Date of Birth' fields. If it does not include the 'Date of Birth' field then you are in a community.
1. Can you provide us with an example of a name you are trying to search?
  A. This way we can check if that names exists or not in our database.
1. Can you confirm the browser and platform you were using when you saw this? 
  A. You specified this was iB&O and Chrome, we are not sure what you mean by this.
1. Can you be a bit more concise on the expected behavior?
  A. You entered `"bullcrap dont show info"`. We work hard to address any issues that any of our users are seeing, but providing us with this is not informative nor constructive for our development team.

Once we have proper a complete answers to all the above questions, then our team can begin investigating the issue.

Thank you!
