### ISSUE TITLE
Account has been randomly wiped

### ISSUE THREAD

**Issue by bloodyshoot64** [Linesmerrill/police-cad#243]
So today i logged back in to my account to do some more roleplays but then j realized that my account was wiped, my civilians that i created are gone. The main civilian was Bob Russel (can't remember the date of birth i put in) but i would like to get my civilians back as i love roleplays and on Bob Russel i had many cars saved to him

To resolve this issue i want my civilian Bob Russel back. I can remember some number plates of the cars that were registered to Bob Russel
Ubermacht oracle xs - yellow - 24xmv375
Infernus classic - dark blue - 85xsk681
Ruiner - two tone red and black - 04rxc734
Vapid Nebula turbo - baige - 66ppm296
Weeny dynasty - red/black - 85plm966

Device - oppo a5 2020
Os - android 9.0
Browser - Samsung internet

**Comment by bloodyshoot64** [comment]
Im so stupid I thought this was contacting the github not creating a community question hahahah anyways if someone can help then I'd Appreciate it

**Comment by Linesmerrill** [comment]
Hi @bloodyshoot64 ! We did find some very old data in our database that could not be updated to our new system. Due to this we had to remove some of the very old accounts. We apologize for any inconvenience with this. We recommend trying to recreate that character and vehicles with your account. Thank you.
