### ISSUE TITLE
Communities

### ISSUE THREAD

**Issue by Allaboutduhmoney** [Linesmerrill/police-cad#255]
**Describe the bug**
[_A clear and concise description of what the bug is._]

- I can only be in one community for some reason. All my information is saved but when I join a new community I lose access to all others.

**To Reproduce**
[_Steps to reproduce the behavior:_]

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by Linesmerrill** [comment]
Hi @Allaboutduhmoney ! Thanks for submitting this bug. This is actual how we designed the website. Do you see a use case when you would actively be in several communities at the same time?

Because communities have completely separate databases for civilians, vehicles etc, we thought that keeping those separate would not only help keep your communities clean, but also reduce the load on the database when searching for names. We don't have any plans in the near future to change this functionality, but we can always aim for it in the future.

Thanks!
