### ISSUE TITLE
[Tutorial] Explain how the Dispatch portion works

### ISSUE THREAD

**Issue by Linesmerrill** [Linesmerrill/police-cad#350]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- Brief tutorial on how the dispatch portion of the site works. Post to the LPS Youtube channel

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by MatheusSilvaBR** [comment]
Hello, how are you?

Your CAD project is incredible, in my opinion the best system for free. I live in Brazil and yes, there are people using your CAD!
However, we have no active community, few players take the word PR seriously. Me and my friend, we used his CAD to play a capture in GTA, just me and him, as I said it is rare to find someone and we have separated some tips and suggestions for improving your project:

. Who is not participating in a community and needs to search for the name of a citizen, it is necessary to search for the date of the civilian, in gta offline if you take a plate any 90% will have some registration, because your CAD is very famous, but good part of the time does not have the date, the person does not record the date of birth;

. For those with a gun registration, the police officer cannot search because the data is not in the ID;

. I found a more complete map, more postcards and 4k, if you want me to send you the file I'll send it to you;

. I am a layman in this matter of software, numbers and codes but it would be interesting for the player who is on the PC and on the cell phone to have an option to search for a postcard, and the image redirects to the postcard, making it easier for the police to search for the requested postcard.

That's it man, sorry for my English I asked the translator for help I hope you understood and congratulations to the project, a big hug from Brazil !!!

**Comment by Linesmerrill** [comment]
@MatheusSilvaBR thanks for all the suggestions! To fix most of the issues you listed, I would suggest you create a community for you and your friends. This greatly reduces the number of possible civilians, vehicles and guns as the only ones you will see, will be the ones you have created in that community.

If you would like to see us add or modify anything please create a ticket here: https://github.com/Linesmerrill/police-cad/issues/new/choose

Thanks!
