### ISSUE TITLE
License Bug

### ISSUE THREAD

**Issue by HotelTravago** [Linesmerrill/police-cad#353]
I've noticed that once you create a license for a civilian, if you update (just click the update button) causes the license to disappear. 

**to produce the bug to happen:**
1. go to edit civilian
2. create a license if not already done
3. once loaded back in, go back into edit civilian
4. press the update button (bug happens whether you actually update any information or just click it in general)
5. go back into the edit civilian one last time, and you will notice that your license has deleted itself

**Expected behavior**
What I expected to see after this process was for the license for this civilian to remain, and not be effected by updating the character. 

- 

**Screenshots**
Sorry no screenshots

- 

**Desktop (please complete the following information):**
 - OS: HP Windows 10
 - Browser Google Chrome
 - Version 86.0.4240.198

**Smartphone (please complete the following information):**
Didn't use a smartphone

**Additional context**
I believe all has been explained to my ability

-

**Comment by Linesmerrill** [comment]
Hello @HotelTravago thanks for creating this. This is actually the expected behavior of the current licenses that we have. Like in real life, if you were to change address or change your name, you would need to get a new license. We mimic that in our CAD to create a bit more realism. So if you update your civilians name or other details you will need to go back in and click on the 'generate license' button. Some servers require that you visit like a DMV (department of motor vehicles) to get a new license. Feel free to RP that how ever you like.

If you think we should change the functionality I am always open to suggestions! Thanks!
