### ISSUE TITLE
feature: add sound effects for panic button and signal 100

### ISSUE THREAD

**Issue by lawsonDevvv** [Linesmerrill/police-cad#448]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- Adding sound effects for panic buttons and Signal 100.

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

- Sound effects for units tabbed out of CAD would be tremendous for response time and awareness, as well as the fact that it'd be more realistic.

**Comment by Linesmerrill** [comment]
Hi @lawsonDevvv, thanks for the feature request. We actually already have this functionality built into the website. You can active it by following these steps:

1. Log into the website, for this example I will log in as a civilian.
2. On the Civilian dashboard click on the account button in the top right.
<img width="783" alt="Screen Shot 2021-05-10 at 7 29 20 PM" src="https://user-images.githubusercontent.com/15384983/117749313-64efa500-b1c6-11eb-899c-b95c93e96e07.png">

3. Now click on the Settings tab and then click to enable sound
<img width="593" alt="Screen Shot 2021-05-10 at 7 30 05 PM" src="https://user-images.githubusercontent.com/15384983/117749347-7c2e9280-b1c6-11eb-86db-d013ec77a017.png">

4. This will enable sound for both the panic button and also signal 100's. Because we do not want to blast your ear drums, we have the sound turned down a bit on the website. So try turning your sound up to around 50% and see if you can hear it.
5. A know limitation is that some phones do not allow us to play sound from the browser. So you can either try running it on a computer or try a different web application on your phone (i.e. Google Chrome is preferred)
