### ISSUE TITLE
No dropdown warning & ticket

### ISSUE THREAD

**Issue by TanguyOrtegat** [Linesmerrill/police-cad#45]
No dropdown for giving warrant

![image](https://user-images.githubusercontent.com/17274032/70641601-27d45b80-1c3e-11ea-84ef-2bf27bab28f7.png)

**Comment by TanguyOrtegat** [comment]
Now I can see dropdown, weird ... will leave it open, maybe a bug...

**Comment by Linesmerrill** [comment]
Hi @TanguyOrtegat! Thanks for opening this. This was part of a quick beta release we accidently pushed out to the public. We saw pretty terrible performance related issues with this release so we reverted back to a stable version. We have since ditched this feature, so that is probably why it no longer shows up like this in the CAD. I'm going to close this as we reverted back the version on our side.
