### ISSUE TITLE
name database dropdown

### ISSUE THREAD

**Issue by TanguyOrtegat** [Linesmerrill/police-cad#48]
When searching for a civil in the name database section, it would be cool to have a dropdown to immediatly select the correct person. Here when you type wrongly or only types first name or last name the cad won't accept.

**Comment by Linesmerrill** [comment]
Hi @TanguyOrtegat thanks for the suggestion! Yeah I actual have this on a feature branch currently, only issue is I am seeing now are performance related. Because there are over 30k civilian names, this database query was taking a long time and using up tons of RAM. This would then crash the server and not provide the quality user experience we are looking for. If we were to find an efficient way to cache that information or retrieve it in a much more performant way, I would feel more confident releasing this feature.

For now i'll keep this open until we can prioritize this among our current backlog 👍

**Comment by Linesmerrill** [comment]
Now we can search for civilians by first name and last name and DOB. This searches the DB and will return all matches: https://github.com/Linesmerrill/police-cad/pull/101. Closing this as completed.
