### ISSUE TITLE
Copy Civilians to New Communities

### ISSUE THREAD

**Issue by iFireSnowzy** [Linesmerrill/police-cad#641]
- I would Love to have a way to copy your civilian, cars, and guns to another community or have your civilian, saved so you don't have to remake them evetime you join a new community.

**Comment by Linesmerrill** [comment]
Yeah this is a bit tricky since right now each civilian can only be tied to a single community. So we would need to rework how civilians are created.

I think ideally they would be registered under the users name and then they can belong in many communities or not.

This would be a large amount of work to implement since it would be a large change from how it currently works under the covers.

One alternative suggestion: so rather than copying, what if we allowed you to just move certain civilians to different communities? So there would still be that same civilian, with the same tickets, history etc but it would not be moved to a new community? Would that work for you?

**Comment by iFireSnowzy** [comment]
It would not work for me, I would love if y’all can have it where you create a civ and it will be linked to your account, and you could make it where there would be a recently creative thing where you can just paste it to a different community.
  
  
  
  
  
  
  

  
  
>

**Comment by Linesmerrill** [comment]
Got it! Thanks for the suggestion

**Comment by Linesmerrill** [comment]
Quick question, when you copy/paste to the new community would that civilian contain all the previous history of the original? or just be a shallow copy with just the civilian?

**Comment by Linesmerrill** [comment]
+1
